# See https://docs.ansible.com/ansible/latest/dev_guide/collections_galaxy_meta.html

namespace: swisstxt
name: harbor
version: 0.3.0
readme: README.md
authors:
  - Joshua Hügli (github.com/joschi36)
description: A collection of modules to manage Harbor over API
license_file: LICENSE
tags:
  - harbor
  - docker
  - registry
repository: https://github.com/swisstxt/ansible-collection-harbor
#documentation: https://github.com/ansible-collection-migration/community.REPO_NAME/tree/main/docs
homepage: https://github.com/swisstxt/ansible-collection-harbor
issues: https://github.com/swisstxt/ansible-collection-harbor/issues
build_ignore:
# https://docs.ansible.com/ansible/devel/dev_guide/developing_collections.html#ignoring-files-and-folders
  - .gitignore
  - changelogs/.plugin-cache.yaml
